version: '3'

services:
  nginx-proxy:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always

  nginx-container1:
    image: nginx:latest
    volumes:
      - ./html/index.html:/usr/share/nginx/html/index.html
    restart: always

  nginx-container2:
    image: nginx:latest
    volumes:
      - ./html/index1.html:/usr/share/nginx/html/index1.html
    restart: always
